language: node_js
node_js:
- 7
branches:
  only: master
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run build
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    local_dir: build
    on:
      branch: master
